# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-24 02:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farmacias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('comuna_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('localidad_nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('local_direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('funcionamiento_hora_apertura', models.CharField(blank=True, max_length=200, null=True)),
                ('funcionamiento_hora_cierre', models.CharField(blank=True, max_length=200, null=True)),
                ('local_telefono', models.CharField(blank=True, max_length=200, null=True)),
                ('local_lat', models.IntegerField(blank=True, null=True)),
                ('local_lng', models.IntegerField(blank=True, null=True)),
                ('medicamento', models.CharField(blank=True, max_length=200, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['local_nombre'],
                'db_table': 'farmacias',
                'managed': False,
            },
        ),
    ]
